environment_variables: {}
external_package_dirs: []
model_metadata: {}
model_name: null
python_version: py38
requirements:
- fairscale
- numpy
- sentencepiece
- torch
resources:
  accelerator: A10G
  cpu: "2"
  memory: 10Gi
  use_gpu: true
secrets: {}
system_packages: []
environment_variables:
  RANK: 0
  WORLD_SIZE: 1
