environment_variables: {}
external_package_dirs: []
model_metadata: {}
model_name: null
python_version: py38
requirements:
- fairscale
- numpy
- sentencepiece
- torch
resources:
  accelerator: null
  cpu: "2"
  memory: 10Gi
  use_gpu: true
secrets: {}
system_packages: []
