environment_variables: {}
external_package_dirs: []
model_metadata: {}
model_name: null
python_version: py311
requirements:
- fairscale
- numpy
- sentencepiece
- torch
resources:
  accelerator: null
  cpu: 500m
  memory: 512Mi
  use_gpu: false
secrets: {}
system_packages: []
